use_frameworks!

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'SwiftyRedux_Example' do
  pod 'SwiftyRedux', :path => '../', :subspecs => ['All'], :testspecs => ['Core/Tests'], :inhibit_warnings => false

  target 'SwiftyRedux_Tests' do
    inherit! :search_paths

  end
end
