# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2

language: objective-c
podfile: Example/Podfile

branches:
  only:
  - master

matrix:
  include:
  - xcode_sdk: iphonesimulator10.0
  - xcode_sdk: iphonesimulator10.1
  - xcode_sdk: iphonesimulator10.2
  - xcode_sdk: iphonesimulator10.3
  - xcode_sdk: iphonesimulator11.0
  - xcode_sdk: iphonesimulator11.1
  - xcode_sdk: iphonesimulator11.2
  - xcode_sdk: iphonesimulator11.3
  - xcode_sdk: iphonesimulator11.4
  - xcode_sdk: iphonesimulator12.0
  - xcode_sdk: iphonesimulator12.1
  - xcode_sdk: iphonesimulator12.2


script:
- pod lib lint --allow-warnings
