# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1

language: objective-c
cache: cocoapods
podfile: Example/Podfile

branches:
  only:
  - master

before_script:
- pod repo update

script:
- pod lib lint --allow-warnings
